name: Deploy to DEV

on:
  pull_request:
    branches: [main]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip python3-venv git -y
          python3 -m venv dagster_env
          source dagster_env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt