name: Validate PR

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip python3-venv git -y

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python packages
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install dagster==1.12.4 dagster-dg-cli dagster-webserver
          pip install -r requirements.txt

      - name: Check Python version
        run: |
          source venv/bin/activate
          mkdir -p ~/dagster_home
          python --version
          dagster --version
          pip install -e .
          dg check defs

      - name: Run dagster daemon
        run: |
          source venv/bin/activate
          export DAGSTER_HOME=~/dagster_home
          dagster-daemon run

      - name: Run dagster webserver
        run: |
          source venv/bin/activate
          export DAGSTER_HOME=~/dagster_home
          dagster-webserver -h 0.0.0.0 -p 3000 -w workspace.yaml
